#!/usr/bin/env bash
# Nightly hallu pipeline: pull main, run full opencite pipeline with GPU
# scoring, push results to an auto-update branch, open a PR. Designed to
# run from cron at 03:00 PDT (see crontab installed alongside this script).
#
# Locking: flock prevents concurrent runs. Logs land in $REPO_DIR/.logs/.
# Safety: a `git reset --hard origin/main` runs before any pipeline step,
# so this script assumes the working tree is disposable between runs.
set -uo pipefail

REPO_DIR="$HOME/dataset_citations"
LOG_DIR="$REPO_DIR/.logs"
LOCK_FILE="$REPO_DIR/.cron.lock"
TS="$(date -u +%Y-%m-%dT%H-%M-%SZ)"
LOG="$LOG_DIR/cron-$TS.log"

mkdir -p "$LOG_DIR"

# Single-writer lock; concurrent invocations short-circuit instead of clobbering each other.
exec 200>"$LOCK_FILE"
if ! flock -n 200; then
  echo "[hallu-cron $TS] another run in progress, skipping" | tee -a "$LOG_DIR/cron-skips.log"
  exit 0
fi

# Tee all subsequent output to the timestamped log file.
exec > >(tee -a "$LOG") 2>&1

trap 'rc=$?; if [ $rc -ne 0 ]; then echo "FAILED rc=$rc at line $LINENO"; fi' EXIT

echo "=== hallu-cron $TS start (host=$(hostname), pid=$$) ==="
cd "$REPO_DIR"

# Pull the GitHub token from gh CLI. cron jobs run with a minimal env;
# without this, dataset-citations-retrieve-metadata falls back to the
# unauthenticated public API (60 req/hr) and stalls after a handful of
# repos. gh stores the token in ~/.config/gh/hosts.yml from a prior
# `gh auth login`; we never have to write it to disk.
export GITHUB_TOKEN="$(gh auth token 2>/dev/null)"
if [ -z "${GITHUB_TOKEN:-}" ]; then
  echo "ERROR: gh auth token returned empty; aborting" >&2
  exit 2
fi

# Reset working tree to fresh main so each cron run starts from a known good state.
git fetch --quiet origin main
git checkout --quiet main
git reset --quiet --hard origin/main
git clean --quiet -fd citations/.checkpoints/ 2>/dev/null || true
echo "main at $(git rev-parse --short HEAD)"

# 1. Discover via catalog (api.nemar.org/datasets, no GitHub for this step).
echo "--- discover ---"
uv run dataset-citations-discover \
  --source catalog \
  --output-file /tmp/hallu_cron_discovered.txt \
  --no-catalog-cache

# 2. Fetch citations via opencite. Skip-existing (7d) keeps the run cheap.
echo "--- update (skip-existing default 7d) ---"
OPENCITE_CONCURRENCY=4 \
  uv run dataset-citations-update \
    --dataset-list-file /tmp/hallu_cron_discovered.txt \
    --output-dir citations/

# 3. Retrieve dataset metadata from GitHub (hallu's own IP = own rate-limit budget).
echo "--- retrieve-metadata ---"
uv run dataset-citations-retrieve-metadata \
  --citations-dir citations/json_opencite \
  --output-dir datasets

# 4. Semantic confidence scoring on RTX 4090. --skip-existing is a small speedup
#    for unchanged citation files.
echo "--- score-confidence (cuda) ---"
uv run dataset-citations-score-confidence \
  --citations-dir citations/json_opencite \
  --datasets-dir datasets \
  --device cuda \
  --skip-existing

# Bail cleanly if no tracked data changed (typical when nothing is stale).
if git diff --quiet citations/ datasets/; then
  echo "no tracked data changes, nothing to commit"
  exit 0
fi

# Commit + push to a timestamped branch; open a PR (manual merge gates the deploy).
BRANCH="auto-update/$TS"
git checkout -b "$BRANCH"
git add citations/ datasets/
DIFFSTAT="$(git diff --cached --stat | tail -5)"
git commit -m "data: hallu nightly pipeline ($TS)

GPU semantic scoring on RTX 4090. Pipeline:
  catalog discover -> opencite fetch -> metadata -> score-confidence

$(echo "$DIFFSTAT")"

git push -u --quiet origin "$BRANCH"

PR_URL=$(gh pr create --base main --head "$BRANCH" \
  --title "Nightly pipeline: $TS" \
  --body "Auto-generated by hallu cron (03:00 PDT). GPU-scored on RTX 4090.

Diffstat:

\`\`\`
$DIFFSTAT
\`\`\`

Auto-merging on green CI. Cloudflare deploy fires via deploy-dashboard.yml's push trigger.")
echo "PR: $PR_URL"

# Auto-merge once CI is green. Data PRs have no human-reviewable
# content; CI is the only gate. --merge preserves commit history
# (no squash), --delete-branch keeps the remote tidy.
gh pr merge --auto --merge --delete-branch "$PR_URL"
echo "auto-merge enabled on $PR_URL"
echo "=== hallu-cron $TS done ==="
